# Generated by Django 4.2.4 on 2024-05-15 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="etc", max_length=100, verbose_name="Category name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="restaurant name"),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/restaurant/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=200, verbose_name="restaurant location"
                    ),
                ),
                (
                    "bannerimage",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/restaurant/",
                        verbose_name="bannerimage",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="introduction"
                    ),
                ),
                ("time", models.CharField(max_length=50, verbose_name="Opening time")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Restaurant owner",
                    ),
                ),
            ],
        ),
    ]
