# Generated by Django 4.2.4 on 2024-05-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant2", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant2.restaurant",
                verbose_name="Restaurant",
            ),
            preserve_default=False,
        ),
    ]
