# Generated by Django 4.2.4 on 2024-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant2", "0005_table_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.PositiveIntegerField(),
        ),
    ]
