# Generated by Django 4.2.4 on 2024-05-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant2", "0006_alter_table_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="restaurant2.restaurant",
                verbose_name="Restaurant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="restaurant2.table"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="restaurant2.menuitem"
            ),
        ),
    ]
