# Generated by Django 5.0.2 on 2024-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_seller",
                    models.BooleanField(default=False, verbose_name="Seller"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Administrator"),
                ),
            ],
            options={
                "verbose_name_plural": "1. User information",
            },
        ),
    ]
