# Generated by Django 5.0.2 on 2024-05-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="etc", max_length=100, verbose_name="Category name"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "1. Category types",
                "db_table": "categoryrestaurant",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_prices", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Done", "Done"),
                            ("Active", "Active"),
                            ("Finish", "Finish"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Store name")),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="logo"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="store location"),
                ),
                (
                    "bannerimage",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/",
                        verbose_name="bannerimage",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="introduction"
                    ),
                ),
                ("time", models.CharField(max_length=50, verbose_name="time")),
            ],
            options={
                "verbose_name_plural": "2. Restaurant",
                "db_table": "storerestaurant",
            },
        ),
        migrations.CreateModel(
            name="FoodsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="product name")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurant.categorymodel",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Food list",
                "db_table": "goodsrestaurant",
            },
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "foods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.foodsmodel",
                        verbose_name="Foods",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "5. Foods image list",
                "db_table": "imagerestaurant",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orderitem",
                        to="restaurant.foodsmodel",
                    ),
                ),
            ],
        ),
    ]
