# Generated by Django 4.2.4 on 2024-05-14 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodimages",
            old_name="foos",
            new_name="foods",
        ),
    ]
