# Generated by Django 4.2.4 on 2024-05-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_rename_foos_foodimages_foods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(max_length=200, verbose_name="restaurant location"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=100, verbose_name="restaurant name"),
        ),
    ]
