# Generated by Django 4.2.4 on 2024-05-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_alter_restaurant_address_alter_restaurant_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(max_length=100, verbose_name="menu"),
        ),
    ]
