# Generated by Django 4.2.4 on 2024-05-14 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_alter_food_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodimages",
            old_name="foods",
            new_name="food",
        ),
    ]
